### PR TITLE
Fixes for #19 and #20

### PR DESCRIPTION
**Pull request by tippyweb**
For #20, the text logo is now moved upward slightly to match the
original AB text logo position.

### CODE REVIEW

**Review by nowucca — CHANGES_REQUESTED** [review]
Please remove the XML files, likely by removing them and committing and pushing the deletes to your GitHub repo.

Also, please edit the other files to remove old commented-out code.

**Review by nowucca — CHANGES_REQUESTED** [review]
Looks like it might work, I'll need to see how to test these changes out easily on my machine.

In the meantime, please remove all the commented code here as well.  Thanks!

**Comment by tippyweb** [comment]
Commented old code was deleted.  Please let me know if you still see some issues.  Thank you!

**Comment by nowucca** [comment]
Deborah,

 All the fixes look great visually, and in the css, so if you could push to YOUR master on github with the extra code and files deleted, let's merge it!

- Dr A
sab-pr-21-confirmation

**Review by nowucca — APPROVED** [review]

**Comment by nowucca** [comment]
Thanks so much Deborah!

**Pull request merged**
